### ISSUE TITLE
Looking for some help

### ISSUE THREAD

**Issue by xuejianchao** [frehner/modern-guide-to-packaging-js-library#12]
Hey!

I'm just reading this article, and got a little confused by the part in brackets of this sentence: 
**Instead, we want to focus on things that apply to every library and bundler (or lack of bundler).**

So, does the "lack of bundler" means this kind of scenario, that we want to package a library, but using no bundler?

Thanks!

**Comment by frehner** [comment]
Yes exactly. Whether you use a bundler or not in your library, these things should all still apply! 👍
