### ISSUE TITLE
Typical webpack skips node_modules

### ISSUE THREAD

**Issue by thewillhuang** [frehner/modern-guide-to-packaging-js-library#15]
Is esNext for libraries a good idea? I distinctly remember as a developer I do not actively run babel through node_modules and when I do, it is only for a few libraries not supporting old browsers

**Comment by frehner** [comment]
Hello, please refer to the web.dev article linked in this section for more details. Thanks!

https://github.com/frehner/modern-guide-to-packaging-js-library#target-modern-browsers

**Comment by frehner** [comment]
Additionally, the wording there will get a slight update when I merge https://github.com/frehner/modern-guide-to-packaging-js-library/pull/10

**Comment by frehner** [comment]
Closing for now, but feel free to ask more questions!
