### ISSUE TITLE
`exports` advice is potentially wrong for types

### ISSUE THREAD

**Issue by Zamiell** [frehner/modern-guide-to-packaging-js-library#35]
Hello, and thanks for the excellent guide.

When setting up my library, I followed this guide and copy-pasted the `exports` example provided here:
https://github.com/frehner/modern-guide-to-packaging-js-library?tab=readme-ov-file#define-your-exports

However, after I published my library and then used publint, it flagged my package.json file for this:
https://publint.dev/rules#export_types_invalid_format

Thus, I think that the posted example is wrong, and it should be updated to satisfy this lint rule.

**Comment by frehner** [comment]
Yeah, at the time this was posted, there was still a lot of confusion and discussion around this. 

In any case, do you think updating things to more along their example would be better?

```json
{
  "exports": {
    "import": {
      "types": "./index.d.mts",
      "default": "./index.mjs"
    },
    "require": {
      "types": "./index.d.cts",
      "default": "./index.cjs"
    }
  }
}
```

**Comment by Zamiell** [comment]
I'm a complete noob, so don't listen to anything I have to say.

With that said, aren't the "default" and "module" fields missing now? So shouldn't it be something like this?

```jsdon
  "exports": {
    ".": {
      "module": "./dist/index.mjs",
      "import": {
        "types": "./dist/index.d.mts",
        "default": "./dist/index.mjs"
      },
      "require": {
        "types": "./dist/index.d.cts",
        "default": "./dist/index.cjs"
      },
      "default": "./dist/index.mjs"
    }
  },
```

**Comment by Zamiell** [comment]
What I posted above passes publint, but it actually fails arethetypeswrong:

![image](https://github.com/frehner/modern-guide-to-packaging-js-library/assets/5511220/58cbe40e-ad25-4c57-bcf7-322cab057453)

So I guess more tweaking is necessary.

**Comment by Zamiell** [comment]
Oh, nevermind, that was just because I was missing the base types.
So the advice should actually be this:

```json
  "exports": {
    ".": {
      "module": "./dist/index.mjs",
      "import": {
        "types": "./dist/index.d.mts",
        "default": "./dist/index.mjs"
      },
      "require": {
        "types": "./dist/index.d.cts",
        "default": "./dist/index.cjs"
      },
      "default": "./dist/index.mjs"
    }
  },
  "types": "./dist/index.d.ts",
```

**Comment by frehner** [comment]
Hmm, do you think we need the subobject with "types" for "module" and "default" as well?

**Comment by Zamiell** [comment]
As I said above, I have no idea, don't trust me. =p

Isn't "module" supposed to be just for webpack? Naively, I wouldn't ever expect webpack to ever need to resolve types, that would only be a type-checking thing via either TypeScript compiler itself or a tool like [stc](https://github.com/dudykr/stc).

As for "default", I guess you could make an argument where there could be some hypothetical future where a `use` keyword is invented as a new kind of import, and then `tsc` needs to resolve the types for it. So then if someone had "types" in "default", then this would work out of the box without having to change anything, assuming that `use` was backwards compatible with a `.d.mts` file. So that's a reason to include it there.

But on the other hand, I'm not super happy about having to pollute my package.json file with all of these repetitive fields that all point to the same file anyway, and the added value here seems to be pretty marginal.

**Comment by frehner** [comment]
>and the added value here seems to be pretty marginal.

Agreed.

Glad we had the discussion, and now it's preserved for future reference as well.

Would you like to create a PR to update it?
